    FROM python:3.9-slim

    WORKDIR /app

    COPY app/frontend/requirements.txt .
    RUN pip install -r requirements.txt

    COPY app/frontend/app.py .

    EXPOSE 8501

    CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--browser.gatherUsageStats=false"]