FROM ultralytics/ultralytics:8.3.162-python

WORKDIR /app

COPY app/backend/requirements.txt .
RUN pip install -r requirements.txt

COPY models/* /app

COPY app/backend/app.py .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]